### ISSUE TITLE
node 12がサポート切れしている

### ISSUE THREAD

**Issue by nmatsui** [Personal-Data-Linkage-Module/pxr-operator-service#2]
# 現在の状況
dockerコンテナのベースイメージとして`node:12`が使われているが、node.js 12系は2022/04/30に保守期限が切れており、セキュリティ上問題がある。
https://github.com/Personal-Data-Linkage-Module/pxr-operator-service/blob/5ade8b82869f6b8fa9295f6b70dcad4fedd3aea3/Dockerfile#L5
```
~$ docker run -it node:12 /bin/bash
root@e8da11beb712:/# node -v
v12.22.12
```

# 修正内容
* ベースイメージをサポート中のLTSであるnode.js 18系以降に変更し、依存ライブラリ等も合わせて更新して動作確認を行う
```[tasklist]
### Tasks
```

**Comment by itoshot** [comment]
## 補足事項
本修正では依存関係を解決していないため、以下コマンドによるnpm installが必要
```bash
npm install --save-dev --legacy-peer-deps
```

## 残課題
`npm audit fix`が通らないため、依存関係の解決が必要
